sonar-project.properties
sonar.projectKey=tasklist-glenn
sonar.projectName=Tasklist Frontend GLENN
sonar.sources=src
sonar.exclusions=src/__tests__/**
sonar.tests=src/__tests__
sonar.test.inclusions=src/tests/*/.test.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr
